minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
architectury_loom_version=1.10.455
architectury_plugin_version=3.4.164
architectury_api_version=13.0.8
fabric_loader_version=0.17.2
fabric_api_version=0.116.17+1.21.1
neoforge_version=21.1.222
cobblemon_version=1.8.1+1.21.1
cobblemon_curse_id=687131
cobblemon_fabric_file=8868927
cobblemon_neoforge_file=8868914

mod_id=alphacandy
mod_name=Alpha Candy
mod_version=1.0.0
maven_group=com.alphacandy
archives_base_name=alpha-candy
enabled_platforms=fabric,neoforge

org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
